CREATE TABLE `osc_report_new` (
  `record_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ukey` varchar(255) NOT NULL,
  `date_key` int(8) unsigned NOT NULL,
  `week_key` int(11) NOT NULL DEFAULT '0',
  `report_key` varchar(255) NOT NULL,
  `00h` int(11) NOT NULL DEFAULT '0',
  `01h` int(11) NOT NULL DEFAULT '0',
  `02h` int(11) NOT NULL DEFAULT '0',
  `03h` int(11) NOT NULL DEFAULT '0',
  `04h` int(11) NOT NULL DEFAULT '0',
  `05h` int(11) NOT NULL DEFAULT '0',
  `06h` int(11) NOT NULL DEFAULT '0',
  `07h` int(11) NOT NULL DEFAULT '0',
  `08h` int(11) NOT NULL DEFAULT '0',
  `09h` int(11) NOT NULL DEFAULT '0',
  `10h` int(11) NOT NULL DEFAULT '0',
  `11h` int(11) NOT NULL DEFAULT '0',
  `12h` int(11) NOT NULL DEFAULT '0',
  `13h` int(11) NOT NULL DEFAULT '0',
  `14h` int(11) NOT NULL DEFAULT '0',
  `15h` int(11) NOT NULL DEFAULT '0',
  `16h` int(11) NOT NULL DEFAULT '0',
  `17h` int(11) NOT NULL DEFAULT '0',
  `18h` int(11) NOT NULL DEFAULT '0',
  `19h` int(11) NOT NULL DEFAULT '0',
  `20h` int(11) NOT NULL DEFAULT '0',
  `21h` int(11) NOT NULL DEFAULT '0',
  `22h` int(11) NOT NULL DEFAULT '0',
  `23h` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`record_id`),
  UNIQUE KEY `ukey_UNIQUE` (`ukey`),
  KEY `report_key` (`report_key`,`date_key`),
  KEY `date_key` (`date_key`,`report_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
