<?php

class Cron_Catalog_DiscountCode_CleanAutoGenerated extends OSC_Cron_Abstract {

    const CRON_TIMER = '0 * * * *';
    const CRON_SCHEDULER_FLAG = 1;

    public function process($data, $queue_added_timestamp) {
        OSC::core('database')->delete('catalog/discount_code', 'auto_generated = 1 AND deactive_timestamp > 0 AND deactive_timestamp < ' . time(), null, 'clean_discount_code');
    }

}
