ALTER TABLE `osc_product_type_variant_amazon_map` ADD COLUMN `plus_price` float NULL AFTER `title`;

UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 3.99 WHERE `product_type_variant_id` = 404;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 9.99 WHERE `product_type_variant_id` = 577;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 3.99 WHERE `product_type_variant_id` = 385;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 8.99 WHERE `product_type_variant_id` = 386;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 6.99 WHERE `product_type_variant_id` = 387;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 6.99 WHERE `product_type_variant_id` = 388;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 6.99 WHERE `product_type_variant_id` = 389;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 6.99 WHERE `product_type_variant_id` = 390;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 6.99 WHERE `product_type_variant_id` = 391;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 6.99 WHERE `product_type_variant_id` = 394;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 19.99 WHERE `product_type_variant_id` = 395;
UPDATE `osc_product_type_variant_amazon_map` SET `plus_price` = 29.99 WHERE `product_type_variant_id` = 396;

-- update product description amazon
UPDATE `osc_catalog_product_description_by_amazon` SET `niche_title` = 'Best Friends Mugs (Chritsmas)' WHERE  `niche_id` = 4;
UPDATE `osc_catalog_product_description_by_amazon` SET `niche_title` = 'Mother & Daughter Mugs (Chritsmas)' WHERE `niche_id` = 5;
UPDATE `osc_catalog_product_description_by_amazon` SET `niche_title` = 'Sisters Mugs (Chritsmas)' WHERE `niche_id` = 6;
UPDATE `osc_catalog_product_description_by_amazon` SET `product_type_ids` = ',11,12,' WHERE `niche_id` = 7;


UPDATE `osc_catalog_product_description_by_amazon` SET `product_type_ids` = ',11,12,' WHERE `niche_id` = 8;
UPDATE `osc_catalog_product_description_by_amazon` SET `product_type_ids` = ',11,12,' WHERE `niche_id` = 9;


INSERT INTO `osc_catalog_product_description_by_amazon`(`id`, `product_type_ids`, `niche_id`, `niche_title`, `description`, `key_product_features`, `keywords`, `added_timestamp`, `modified_timestamp`) VALUES (10, ',11,12,', 10, 'Dog Blanket', 'Made from soft fleece material, our [Quote] snuggly personalized dog blanket is a wonderful item for both dog lovers and their fur friends to keep feeling cozy when it comes to a cold day. As it\'s customizable with names and images of the owners and dogs, this dog blanket would be truly a treasured keepsake, reminding them of an unbreakable connection. Plus, being made from lightweight fleece material, it\'s a perfect dog couch blanket as you and your paw-some friends can lie under it while enjoying your favorite TV shows. \nStart customizing the best custom dog blanket for couch with a few easy steps now! 1. Choose the size, then click customize now! 2. Add your own personal touches 3. Place Order', '{\"key_product_features1\":\"Personalized: Dog blankets are customizable on the front and the back is solid cream. Add your own personal touches (images, names...) to create special custom small and large dog blanket.\",\"key_product_features2\":\"Durable: Cozy plush fleece dog blanket for couch, made of 100% polyester fleece. Machine washable with cold water and tumble dry on low heat. Don\'t dry clean or iron, press with heat.\",\"key_product_features3\":\"Unique: All customizable options are originated by Gossby. Freely add your own personal touches via personalized section to create on-of-a-kind personalized dog blanket.\",\"key_product_features4\":\"Functional: Perfect to be a decorative bed blanket, fleece dog blanket for couch, or using as a tapestry by hanging on the wall. It would be the best dog lover gift.\",\"key_product_features5\":\"Guarantee: 100% MONEY BACK GUARANTEE. Get a 100% refund if you dislike our product for whatever reason.\"}', 'dog blanket small dog blanket dog blanket for couch personalized dog blanket dog couch blanket fleece dog blanket dog fleece blanket large dog blanket custom dog blanket', 1638464356, 1638464356);
INSERT INTO `osc_catalog_product_description_by_amazon`(`id`, `product_type_ids`, `niche_id`, `niche_title`, `description`, `key_product_features`, `keywords`, `added_timestamp`, `modified_timestamp`) VALUES (11, ',7,8,9,10,34,35,36,37,38,', 11, 'Mother & Daughter Mug (All year)', 'You can expect surprising and emotional reactions from your mom/ your daughter when she\'s given these unique mug, as this has been verified by many thousands of our customers!\r\nSometimes the best gifts come from the heart and that’s when a mother-daughter mug can come in handy. With a touch of customization, the [Quote] personalized mug is a wonderful way to remember all the good times in life with your mother and daughter. This mug is perfect mother daughter gifts for birthdays, mother\'s day, and any other special occasion!', '{\"key_product_features1\":\"Personalized: Customize-easy mother and daughter mug (both sides). Incorporate joyous memories to create the most special cup, dedicated to only your loving mother/daughter.\",\"key_product_features2\":\"Durable: High-quality ceramic mug for everyone. Dishwasher-friendly, microwave-safe with toxin-free printing.\",\"key_product_features3\":\"Unique: Original artworks by Gossby. Add personal touches through the options available to create a one-of-a-kind design, copy-proof.\",\"key_product_features4\":\"Stain Resistant: Heavy-duty protective coating to minimize coffee or tea stains. Easy cleaning by hand or dishwasher.\",\"key_product_features5\":\"Guarantee: 100% MONEY BACK GUARANTEE. Get a 100% refund if you dislike our product for whatever reason.\"}', 'mother daughter mugs mother\'s day gifts mom mug daughter mug mother daughter coffee mugs mug for mom mug for daughter personalized mug for mug customized mug for daughter personalized gifts for mom and daughter', 1638464356, 1638464356);
INSERT INTO `osc_catalog_product_description_by_amazon`(`id`, `product_type_ids`, `niche_id`, `niche_title`, `description`, `key_product_features`, `keywords`, `added_timestamp`, `modified_timestamp`) VALUES (12, ',7,8,9,10,34,35,36,37,38,', 12, 'Best Friends Mug (All year)', 'When sisters stand shoulder to shoulder, who stands a chance against us? This personalized sister mug with names and text, [Quote], will express to your besties how special they are to you. It comes with a beautiful, glossy finish and easy-grip handle. Each BFF mug has printed on both sides that can never come off, adding an aesthetic feel to your coffee drinking game. Gift the mugs to your coffee-loving friends on birthdays, Graduation day, Christmas, and other occasions.', '{\"key_product_features1\":\"Personalized: Customize-easy best friend mug (both sides). Incorporate joyous memories to create the most special cup, dedicated to only your loving besties.\",\"key_product_features2\":\"Durable: High-quality ceramic mug for everyone. Dishwasher-friendly, microwave-safe with toxin-free printing.\",\"key_product_features3\":\"Unique: Original artworks by Gossby. Add personal touches through the options available to create a one-of-a-kind design, copy-proof.\",\"key_product_features4\":\"Stain Resistant: Heavy-duty protective coating to minimize coffee or tea stains. Easy cleaning by hand or dishwasher.\",\"key_product_features5\":\"Guarantee: 100% MONEY BACK GUARANTEE. Get a 100% refund if you dislike our product for whatever reason.\"}', 'friends mugs best friends mugs personalized best friend mugs custom coffee mugs for friends friendship mug friends cup personalized gifts for best friends customized mug for friend', 1638464356, 1638464356);
INSERT INTO `osc_catalog_product_description_by_amazon`(`id`, `product_type_ids`, `niche_id`, `niche_title`, `description`, `key_product_features`, `keywords`, `added_timestamp`, `modified_timestamp`) VALUES (13, ',7,8,9,10,34,35,36,37,38,', 13, 'Sisters Mug (All Year)', 'What would be better than giving your cherished sisters our custom sister mugs to celebrate your sisterhood? This coffee mug [Quote] with personal touches will be treasured keepsakes, reminding you of beautiful relationships.  It’s got great sentimental value while still being practical, so you can be sure that she’ll use it every morning. Just imagine her sipping coffee out of this while at work and smiling at the memory of you. This mug is perfect for birthdays, holidays, and any other special occasion!', '{\"key_product_features1\":\"Personalized: Customize-easy sister mug (both sides). Incorporate joyous memories to create the most special cup, dedicated to only your loving sisters.\",\"key_product_features2\":\"Durable: High-quality ceramic mug for everyone. Dishwasher-friendly, microwave-safe with toxin-free printing.\",\"key_product_features3\":\"Unique: Original artworks by Gossby. Add personal touches through the options available to create a one-of-a-kind design, copy-proof.\",\"key_product_features4\":\"Stain Resistant: Heavy-duty protective coating to minimize coffee or tea stains. Easy cleaning by hand or dishwasher.\",\"key_product_features5\":\"Guarantee: 100% MONEY BACK GUARANTEE. Get a 100% refund if you dislike our product for whatever reason.\"}', 'sister mug sister coffee mug sister coffee mug from sister personalized sister mug custom coffee mug for sister sister cup customized sisters mug big sister cup personalized gifts for sisters', 1638464356, 1638464356);
INSERT INTO `osc_catalog_product_description_by_amazon`(`id`, `product_type_ids`, `niche_id`, `niche_title`, `description`, `key_product_features`, `keywords`, `added_timestamp`, `modified_timestamp`) VALUES (14, ',7,8,9,10,34,35,36,37,38,', 14, 'Dog Mug (All Year)', 'Whether you\'re looking for a practical item to start your morning routine with favorite beverages or something special to surprise any dog lover, this [Quote] personalized dog mug will be what you need. Because it\'s customizable, you can easily add your own personal touches to the dog mug and create a unique dog cup that melts anyone\'s heart. As useful and thoughtful as it is, this is a perfect dog mom mug and dog dad mug to win the giftees\' hearts when it comes to their days.\nStart customizing the best custom dog mug with a few easy steps now! 1. Choose mug size, then click customize now! 2. Add your own personal touches 3. Place Order', '{\"key_product_features1\":\"Personalized: Customize-easy dog mug (both sides). Incorporate joyous memories to create the most special dog cup, dedicated to only your dog lover in life.\",\"key_product_features2\":\"Durable: High-quality ceramic dog mug for everyone. Dishwasher-friendly, microwave-safe with toxin-free printing.\",\"key_product_features3\":\"Unique: Original artworks by Gossby. Add personal touches through the options available to create a one-of-a-kind design, copy-proof.\",\"key_product_features4\":\"Stain Resistant: Heavy-duty protective coating to minimize coffee or tea stains. Easy cleaning by hand or dishwasher.\",\"key_product_features5\":\"Guarantee: 100% MONEY BACK GUARANTEE. Get a 100% refund if you dislike our product for whatever reason.\"}', 'dog mug dog coffee mug dog mom mug personalized dog mug dog lover mug dogs coffee mug dog cup dog dad mug', 1638464356, 1638464356);