ALTER TABLE `osc_catalog_product` ADD COLUMN `supply_location` VARCHAR(3000) NOT NULL DEFAULT '' AFTER `options`;

UPDATE `osc_catalog_product`
SET `supply_location` = ',AF_,AX_,AL_,DZ_,AS_,AD_,AO_,AI_,AQ_,AG_,AR_,AM_,AW_,AU_,AT_,AZ_,BS_,BH_,BD_,BB_,BY_,BE_,BZ_,BJ_,BM_,BT_,BO_,BQ_,BA_,BW_,BV_,BR_,IO_,BN_,BG_,BF_,BI_,KH_,CM_,CA_,CV_,KY_,CF_,TD_,CL_,CN_,CX_,CC_,CO_,KM_,CG_,CD_,CK_,CR_,HR_,CW_,CY_,CZ_,CI_,DK_,DJ_,DM_,DO_,TL_,EC_,EG_,SV_,GQ_,ER_,EE_,ET_,FK_,FO_,FJ_,FI_,FR_,GF_,PF_,TF_,GA_,GM_,GE_,DE_,GH_,GI_,GR_,GL_,GD_,GP_,GU_,GT_,GG_,GN_,GW_,GY_,HT_,HM_,VA_,HN_,HK_,HU_,IS_,IN_,ID_,IR_,IQ_,IE_,IM_,IL_,IT_,JM_,JP_,JE_,JO_,KZ_,KE_,KI_,XK_,KW_,KG_,LA_,LV_,LB_,LS_,LR_,LY_,LI_,LT_,LU_,MO_,MK_,MG_,MW_,MY_,MV_,ML_,MT_,MH_,MQ_,MR_,MU_,YT_,MX_,FM_,MD_,MC_,MN_,ME_,MS_,MA_,MZ_,MM_,NA_,NR_,NP_,NL_,AN_,NC_,NZ_,NI_,NE_,NG_,NU_,NF_,MP_,NO_,OM_,PK_,PW_,PS_,PA_,PG_,PY_,PE_,PH_,PN_,PL_,PT_,QA_,RE_,RO_,RU_,RW_,BL_,SH_,KN_,LC_,MF_,PM_,WS_,SM_,ST_,SA_,SN_,RS_,SC_,SL_,SG_,SX_,SK_,SI_,SB_,SO_,ZA_,GS_,KR_,SS_,ES_,LK_,VC_,SD_,SR_,SJ_,SZ_,SE_,CH_,TW_,TJ_,TZ_,TH_,TG_,TK_,TO_,TT_,TN_,TR_,TM_,TC_,TV_,VI_,UG_,AE_,GB_,US_,UM_,UY_,UZ_,VU_,VE_,VN_,VG_,WF_,EH_,YE_,ZM_,ZW_,PR_,CU_,KP_,CS_,SY_,UA_,AP_,AC_,US_AL,US_AK,US_AS,US_AZ,US_AR,US_AE,US_AA,US_AP,US_CA,US_CO,US_CT,US_DE,US_DC,US_FM,US_FL,US_GA,US_GU,US_HI,US_ID,US_IL,US_IN,US_IA,US_KS,US_KY,US_LA,US_ME,US_MH,US_MD,US_MA,US_MI,US_MN,US_MS,US_MO,US_MT,US_NE,US_NV,US_NH,US_NJ,US_NM,US_NY,US_NC,US_ND,US_MP,US_OH,US_OK,US_OR,US_PW,US_PA,US_PR,US_RI,US_SC,US_SD,US_TN,US_TX,US_UT,US_VT,US_VI,US_VA,US_WA,US_WV,US_WI,US_WY,BR_AC,BR_AL,BR_AP,BR_AM,BR_BA,BR_CE,BR_ES,BR_GO,BR_MA,BR_MT,BR_MS,BR_MG,BR_PA,BR_PB,BR_PR,BR_PE,BR_PI,BR_RJ,BR_RN,BR_RS,BR_RO,BR_RR,BR_SC,BR_SP,BR_SE,BR_TO,BR_DF,CA_AB,CA_BC,CA_MB,CA_NL,CA_NB,CA_NS,CA_NT,CA_NU,CA_ON,CA_PE,CA_QC,CA_SK,CA_YT,AU_ACT,AU_NSW,AU_VIC,AU_QLD,AU_SA,AU_TAS,AU_WA,AU_NT,MX_AGS,MX_BC,MX_BCS,MX_CAMP,MX_CHIS,MX_CHIH,MX_DF,MX_COAH,MX_COL,MX_DGO,MX_GTO,MX_GRO,MX_HGO,MX_JAL,MX_MEX,MX_MICH,MX_MOR,MX_NAY,MX_NL,MX_OAX,MX_PUE,MX_QRO,MX_Q ROO,MX_SLP,MX_SIN,MX_SON,MX_TAB,MX_TAMPS,MX_TLAX,MX_VER,MX_YUC,MX_ZAC,IT_AG,IT_AL,IT_AN,IT_AO,IT_AR,IT_AP,IT_AT,IT_AV,IT_BA,IT_BT,IT_BL,IT_BN,IT_BG,IT_BI,IT_BO,IT_BZ,IT_BS,IT_BR,IT_CA,IT_CL,IT_CB,IT_CI,IT_CE,IT_CT,IT_CZ,IT_CH,IT_CO,IT_CS,IT_CR,IT_KR,IT_CN,IT_EN,IT_FM,IT_FE,IT_FI,IT_FG,IT_FC,IT_FR,IT_GE,IT_GO,IT_GR,IT_IM,IT_IS,IT_AQ,IT_SP,IT_LT,IT_LE,IT_LC,IT_LI,IT_LO,IT_LU,IT_MC,IT_MN,IT_MS,IT_MT,IT_VS,IT_ME,IT_MI,IT_MO,IT_MB,IT_NA,IT_NO,IT_NU,IT_OG,IT_OT,IT_OR,IT_PD,IT_PA,IT_PR,IT_PV,IT_PG,IT_PU,IT_PE,IT_PC,IT_PI,IT_PT,IT_PN,IT_PZ,IT_PO,IT_RG,IT_RA,IT_RC,IT_RE,IT_RI,IT_RN,IT_RM,IT_RO,IT_SA,IT_SS,IT_SV,IT_SI,IT_SR,IT_SO,IT_TA,IT_TE,IT_TR,IT_TO,IT_TP,IT_TN,IT_TV,IT_TS,IT_UD,IT_VA,IT_VE,IT_VB,IT_VC,IT_VR,IT_VV,IT_VI,IT_VT,'
WHERE (`product_id` IN (SELECT product_id FROM `osc_product_variant` WHERE product_type_variant_id = 0));

CREATE TABLE `osc_supply_variant_convert` (
    `id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
    `product_type_variant_id` INT(11) NOT NULL DEFAULT 0,
    `supplier_id` INT(11) NOT NULL DEFAULT 0,
    `supplier_location_rel_id` INT(11) NOT NULL DEFAULT 0,
    `location_parsed` VARCHAR(3000) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB;

/* Run this query after run successfully tool convert data */
RENAME TABLE osc_supply_variant TO osc_supply_variant_tmp, osc_supply_variant_convert TO osc_supply_variant;
