CREATE TABLE `osc_report_record` (
  `record_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `report_key` varchar(255) NOT NULL,
  `report_value` int(11) NOT NULL,
  `ab_test` text,
  `client_ip` varchar(15) DEFAULT NULL,
  `country_code` varchar(2) DEFAULT NULL,
  `referer_url` varchar(255) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `referer_host` varchar(255) DEFAULT NULL,
  `device_type` varchar(100) DEFAULT NULL,
  `device_identifier` varchar(255) DEFAULT NULL,
  `browser_name` varchar(255) DEFAULT NULL,
  `browser_version` varchar(255) DEFAULT NULL,
  `os_name` varchar(100) DEFAULT NULL,
  `os_version` varchar(100) DEFAULT NULL,
  `added_timestamp` int(10) NOT NULL,
  PRIMARY KEY (`record_id`),
  KEY `report_key` (`report_key`,`added_timestamp`),
  KEY `country_code` (`report_key`,`country_code`,`added_timestamp`),
  KEY `referer_host` (`report_key`,`referer_host`,`added_timestamp`),
  KEY `device_type` (`report_key`,`device_type`,`added_timestamp`),
  KEY `device_identifier` (`report_key`,`device_identifier`,`added_timestamp`),
  KEY `browser_name` (`report_key`,`browser_name`,`added_timestamp`),
  KEY `browser_version` (`report_key`,`browser_name`,`browser_version`,`added_timestamp`),
  KEY `os_name` (`report_key`,`os_name`,`added_timestamp`),
  KEY `os_version` (`report_key`,`os_name`,`os_version`,`added_timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
