<?php

OSC_Controller::registerBind('catalog', 'catalog');

OSC_Observer::registerObserver('catalog/productCreated', ['Observer_Catalog_Common', 'productCreated']);
OSC_Observer::registerObserver('catalog/productUpdated', ['Observer_Catalog_Common', 'productUpdated']);
OSC_Observer::registerObserver('catalog/productDeleted', ['Observer_Catalog_Common', 'productDeleted']);

OSC_Observer::registerObserver('backend/collect_menu', ['Observer_Catalog_Backend', 'collectMenu']);

OSC_Observer::registerObserver('navigation/collect_item_type', ['Observer_Catalog_Backend', 'navCollectItemType']);
OSC_Observer::registerObserver('catalog/collectCustomerGroup', ['Observer_Catalog_Backend', 'collectCustomerGroup']);

OSC_Observer::registerObserver('catalog/afterPlaceOrder', ['Observer_Catalog_Common', 'afterPlaceOrder']);
OSC_Observer::registerObserver('catalog/afterPlaceOrder', ['Observer_Catalog_Campaign', 'afterPlaceOrder']);
OSC_Observer::registerObserver('catalog/afterPlaceOrder', ['Observer_Catalog_Review', 'afterPlaceOrder']);
OSC_Observer::registerObserver('catalog/orderVerifyLineItemToCreate', ['Observer_Catalog_Campaign', 'orderVerifyLineItemToCreate']);
OSC_Observer::registerObserver('catalog/orderVerifyUpsaleItemToCreate', ['Observer_Catalog_Campaign', 'orderVerifyUpsaleItemToCreate']);

OSC_Observer::registerObserver('catalog/collect_payment_method', ['Observer_Catalog_Payment', 'collectMethods']);
OSC_Observer::registerObserver('catalog/collect_shipping_carrier', ['Observer_Catalog_Shipping', 'collectRates']);
OSC_Observer::registerObserver('catalog/collect_carrier_tracking_number_pattern', ['Observer_Catalog_Shipping', 'collectCarrierTrackingNumberPatterns']);

OSC_Observer::registerObserver('user/permmask/collect_keys', ['Observer_Catalog_Backend', 'collectPermKey']);

OSC_Observer::registerObserver('parse_full_url', ['Observer_Catalog_Common', 'parseFullUrl']);

OSC_Observer::registerObserver('report_event:catalog/product_view', ['Observer_Catalog_Report', 'recordProductView']);
OSC_Observer::registerObserver('report_event:catalog/add_to_cart', ['Observer_Catalog_Report', 'recordAddToCart']);
OSC_Observer::registerObserver('report_event:catalog/checkout_initialize', ['Observer_Catalog_Report', 'recordCheckoutInitialize']);
OSC_Observer::registerObserver('report_event:catalog/purchase', ['Observer_Catalog_Report', 'recordPurchase']);

OSC_Observer::registerObserver('collect_setting_item', ['Observer_Catalog_Review', 'collectSettingItem']);
OSC_Observer::registerObserver('catalog/preCustomerEditOrder', ['Observer_Catalog_Campaign', 'preCustomerEditOrder']);

OSC_Observer::registerObserver('catalog/cart_lineItem_customize', ['Observer_Catalog_Campaign', 'validateCartItem']);

OSC_Observer::registerObserver('collect_setting_section', ['Observer_Catalog_Backend', 'collectSettingSection']);
OSC_Observer::registerObserver('collect_setting_item', ['Observer_Catalog_Backend', 'collectSettingItem']);
OSC_Observer::registerObserver('collect_setting_type', ['Observer_Catalog_Backend', 'collectSettingType']);

OSC_Observer::registerObserver('collect_ab_test_data', ['Observer_Catalog_Common', 'collectABTestData']);

OSC_Template::registerComponent('catalog_frontend', ['type' => 'template', 'data' => '[frontend_template]catalog/initialize']);
OSC_Cron::registerScheduler('catalog/discountCode_cleanAutoGenerated', null, '@hourly', ['estimate_time' => 60*2]);
OSC_Cron::registerScheduler('catalog/order_afterOrderCreated', null, '* * * * *', ['estimate_time' => 60*60]);
OSC_Cron::registerScheduler('catalog/order_sendMailReview', null, '* * * * *', ['estimate_time' => 60*60]);

OSC_Cron::registerScheduler('catalog/product_getCurrencyRate', null, '0 8 * * *', ['estimate_time' => 60*2]);

OSC_Cron::registerScheduler('catalog/recheckTransaction', null, '*/15 * * * *', ['estimate_time' => 60*60]);
OSC_Cron::registerScheduler('catalog/upsale_updateBillingAgreementToken', null, '0 * * * *', ['estimate_time' => 60*60]);
OSC_Observer::registerObserver('catalog/upsaleCreated', ['Observer_Catalog_Upsale', 'upsaleCreated']);
OSC_Cron::registerScheduler('catalog/cache', null, '* * * * *', ['estimate_time' => 60 * 60]);

OSC_Cron::registerScheduler('catalog/product_autoListingDiscard', null, '*/30 * * * *', ['estimate_time' => 60*60]);

OSC_Observer::registerObserver('initialize', ['Observer_Catalog_Common', 'checkSaleReference']);
OSC_Observer::registerObserver('catalog/cart_collect_client_info', ['Observer_Catalog_Common', 'collectClientInfo']);

//OSC_Observer::registerObserver('model__catalog_product__after_save', ['Observer_Catalog_Common', 'updateCollectionsProductsRel']);
//OSC_Observer::registerObserver('model__catalog_collection__after_save', ['Observer_Catalog_Common', 'updateCollectionsProductsRel']);

OSC_Observer::registerObserver('model__catalog_product__after_save', ['Observer_Catalog_Cache', 'resetCache']);
OSC_Observer::registerObserver('model__catalog_product__row_deleted', ['Observer_Catalog_Cache', 'resetCacheDelete']);

//OSC_Observer::registerObserver('model__catalog_product__after_save', ['Observer_Catalog_Search', 'addSearch']);
OSC_Observer::registerObserver('model__catalog_product__row_deleted', ['Observer_Catalog_Search', 'deleteSearch']);

OSC_Observer::registerObserver('model_catalog_product_save', ['Observer_Catalog_Search', 'addSearch']);

// OSC_Observer::registerObserver('catalog/afterPlaceOrder', ['Observer_Catalog_Common', 'insertProfit']);

//OSC_Cron::registerScheduler('catalog/cart_backup', null, '0 7 * * *', ['estimate_time' => 60*60]);

OSC_Cron::registerScheduler('catalog/collection_genProductByRelativeRange', null, '@daily', ['estimate_time' => 60*60*5]);
OSC_Observer::registerObserver('catalog/algoliaSyncProduct', ['Observer_Catalog_Algolia', 'syncProduct']);
OSC_Cron::registerScheduler('catalog/algolia_partiaUpdate', null, '0 1 * * *', ['estimate_time' => 60*15]);
